apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
      - resources:
        name: registry
        image: registry:2.7.1
        ports:
        - name: registry-port
          containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: images
      volumes:
      - name: images
        hostPath:
          path: /var/lib/registry
      nodeSelector:
        registry: registry
