apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: jhub
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "4"
      requests:
        cpu: "4"
    args:
    - -cpus
    - "4"
