kind: PersistentVolume
apiVersion: v1
metadata:
  name: henry-pv
  namespace: jhub
  labels:
    appname: jupyterhub
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mnt/henry"

