kind: PersistentVolume
apiVersion: v1
metadata:
  name: qinwei-pv
  namespace: jhub
  labels:
    appname: jupyterhub
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mnt/qinwei"

