kind: PersistentVolume
apiVersion: v1
metadata:
  name: test6-pv
  namespace: jhub
  labels:
    appname: jupyterhub
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/code/BDP/data/private/test6"
