kind: ReplicationController
apiVersion: v1
metadata:
  name: hadoop-worker
  namespace: hadoop-v1
spec:
  replicas: 1
  selector:
    component: hadoop-worker
  template:
    metadata:
      labels:
        component: hadoop-worker
    spec:
      containers:
        - name: hadoop-worker
          image: registry.cn-hangzhou.aliyuncs.com/hadoop_iscas/hadoop_cluster:2.7.6
          command: ["/root/scripts/start-worker-hadoop.sh", "hmaster"]
          resources:
            limits:
              cpu: "1"
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 2048Mi
          securityContext:
            privileged: true
